### ISSUE TITLE
Problem - run the app

### ISSUE THREAD

**Issue by manuelvillotti** [MrVannu/MagikMarket#1]
Is there a way to run the program with maven? Or to package creating a jar. I tried opening it with IntelliJ but had problems running main.java (build fails).

**Comment by aleski017** [comment]
Hi Manuel, to open the project, you must download the sdk (if you don't already have it) and link it in the "Edit Configurations" of the project. This is the string: --module-path "C:\your\path\sdk\lib" --add-modules javafx.controls,javafx.fxml
Please feel free to ask if something is unclear and does  not work.
Thank you.

**Comment by manuelvillotti** [comment]
Tried to put the string like this:
<img width="737" alt="Screenshot 2023-09-21 152507" src="https://github.com/MrVannu/MagikMarket/assets/64196748/1ae6a449-021d-46a8-b351-0e723474c14b">

Still, I get the same error

**Comment by manuelvillotti** [comment]
Thaks for support. Issue solved by adding VM options under Run->Edit-Configurations->Modify-Options

**Comment by manuelvillotti** [comment]
Thaks for support. Issue solved by adding VM options under Run->Edit-Configurations->Modify-Options

**Comment by volimroze** [comment]
Hi, can you please send me the instructions on how to run the project?

**Comment by manuelvillotti** [comment]
I solved my issue by:
1. Downloading JavaFX SDK [ https://jdk.java.net/javafx20/ ]
2. opening the project using IntelliJ
3. under Run -> Edit Configuration you will find "Modify options", click "Add VM options"
4. add the string " --module-path "C:\your\path\sdk\lib" --add-modules javafx.controls,javafx.fxml " changing the path to your sdk's lib
5. select the main class to run
6. Run the project from IntelliJ

**Comment by volimroze** [comment]
I used Eclipse for developing my project and I am not familiar with the Intellj Environment. I added the sdk from the instructions(please see the image attached) and I still have the error Error: JavaFX runtime components are missing, and are required to run this application

 Is there another way to run the project?
![Screenshot 2023-09-22 123655](https://github.com/MrVannu/MagikMarket/assets/101053824/35fe2a10-1f6c-4b7b-8224-595bc9bb1137)

**Comment by manuelvillotti** [comment]
Actually I don't know as it isn't my project but seeing your screenshot you wrote the string in the wrong field. Leave that field empty and under modify options press Add VM options. Than you add the string in the vm options

**Comment by volimroze** [comment]
I left the field empty where I had the sdk and added the path to the sdk in the VM Options, and I still can't run it. What should I do? 
![vm empty](https://github.com/MrVannu/MagikMarket/assets/101053824/1fd51fa5-b9b1-4532-aa88-4f5b3dcbbf66)
![vm with sdk](https://github.com/MrVannu/MagikMarket/assets/101053824/74831900-0c41-4eca-9e3d-daad6341853e)
![error](https://github.com/MrVannu/MagikMarket/assets/101053824/23fdad85-8e57-4afe-bd9a-d8f7db8c426b)

**Comment by manuelvillotti** [comment]
did you add the entire string either the path or only the path?

**Comment by volimroze** [comment]
C:\Users\Isidora Erakovic\Downloads\openjfx-20.0.2_windows-x64_bin-sdk\javafx-sdk-20.0.2\lib

**Comment by manuelvillotti** [comment]
try replacing it with this:

--module-path "C:\Users\Isidora Erakovic\Downloads\openjfx-20.0.2_windows-x64_bin-sdk\javafx-sdk-20.0.2\lib" --add-modules javafx.controls,javafx.fxml

**Comment by volimroze** [comment]
It works now thanks!
